### ISSUE TITLE
Can I read conll format and turn it to spacy object?

### ISSUE THREAD

**Issue by shaked571** [BramVanroy/spacy_conll#11]
Can I take a conll format file and transform it in to spacy object using the repo code?
lets say I have the following file: 

      # sent_id = 9
      # text = היא אמרה כי שירות התעסוקה הציע להביא עובדים מדרום לבנון, אך תנועת המושבים סירבה.
      1	היא	הוא	PRON	PRON	Gender=Fem|Number=Sing|Person=3|PronType=Prs	2	nsubj	_	_
      2	אמרה	אמר	VERB	VERB	Gender=Fem|HebBinyan=PAAL|Number=Sing|Person=3|Tense=Past|Voice=Act	0	root	_	_
      3	כי	כי	SCONJ	SCONJ	_	7	mark	_	_
      4	שירות	שירות	NOUN	NOUN	Definite=Cons|Gender=Masc|Number=Sing	7	nsubj	_	_
      5-6	התעסוקה	_	_	_	_	_	_	_	_
      5	ה	ה	DET	DET	Definite=Def|PronType=Art	6	det	_	_
      6	תעסוקה	תעסוקה	NOUN	NOUN	Gender=Fem|Number=Sing	4	compound:smixut	_	_
      7	הציע	הציע	VERB	VERB	Gender=Masc|HebBinyan=HIFIL|Number=Sing|Person=3|Tense=Past|Voice=Act	2	ccomp	_	_
      8	להביא	הביא	VERB	VERB	HebBinyan=HIFIL|VerbForm=Inf|Voice=Act	7	xcomp	_	_
      9	עובדים	עובד	NOUN	NOUN	Gender=Masc|Number=Plur	8	obj	_	_
      10-11	מדרום	_	_	_	_	_	_	_	_
      10	מ	מ	ADP	ADP	_	11	case	_	_
      11	דרום	דרום	NOUN	NOUN	Definite=Cons|Gender=Masc|Number=Sing	8	obl	_	_
      12	לבנון	לבנון	PROPN	PROPN	_	11	compound:smixut	_	SpaceAfter=No
      13	,	,	PUNCT	PUNCT	_	18	punct	_	_
      14	אך	אך	CCONJ	CCONJ	_	18	cc	_	_
      15	תנועת	תנועה	NOUN	NOUN	Definite=Cons|Gender=Fem|Number=Sing	18	nsubj	_	_
      16-17	המושבים	_	_	_	_	_	_	_	_
      16	ה	ה	DET	DET	Definite=Def|PronType=Art	17	det	_	_
      17	מושבים	מושב	NOUN	NOUN	Gender=Masc|Number=Plur	15	compound:smixut	_	_
      18	סירבה	סירב	VERB	VERB	Gender=Fem|HebBinyan=PIEL|Number=Sing|Person=3|Tense=Past|Voice=Act	7	conj	_	SpaceAfter=No
      19	.	.	PUNCT	PUNCT	_	2	punct	_	_

Can I somehow use the code to read the format as spacy doc?

**Comment by BramVanroy** [comment]
Hi @shaked571, this is currently not implemented but does sound like a good addition to the library. I'll try to find time to implement this in the following weeks!

**Comment by shaked571** [comment]
Hi @BramVanroy , thank you for the quick response.
I actually found a similar implementation. I currently work on it for my theses.
It would modify this code:
https://github.com/explosion/spaCy/blob/a1c5b694be117ac92e21f9860309821ad6da06f7/spacy/cli/converters/conllu2json.py#L179-L264
I hope i can find some time myself to send a PR to your repo. 
Always good to give back :)

**Comment by shaked571** [comment]
Ive opened aa PR.
check it out and comment if needed. If you have any comment hope I can find some time in the next 2 weeks or so to fix them.

**Comment by BramVanroy** [comment]
Hi @shaked571, I'll try to have a look tomorrow and if not it'll be the weekend of next week. Since it is largely a copy-paste of the spaCy code, a reference should definitely be included to their code. The docstring format should also be updated. I'll have a look in more detail when I can.

Thanks!

**Comment by shaked571** [comment]
You are correct, I will allow you to point where to put the reference.  and I added some docstrig that were indeed missing
