### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by maartenpt** [BramVanroy/spacy_conll#18]
There seems to be an error in the example at `https://spacy.io/universe/project/spacy-conll`, at least when I try to run it. Instead of `init_parser("stanza","en"` it should say `init_parser("en", "stanza"`

**Comment by BramVanroy** [comment]
Hi Maarten, the snippet on the Universe page is indeed outdated. Will fix it this week. Thanks for signalling it!

**Comment by BramVanroy** [comment]
Fixed by @[ljvmiranda921](https://github.com/ljvmiranda921) in https://github.com/explosion/spaCy/pull/10516
