### ISSUE TITLE
AttributeError: 'spacy.morphology.Morphology' object has no attribute 'tag_map'

### ISSUE THREAD

**Issue by pradeepdev-1995** [BramVanroy/spacy_conll#19]
I am getting the following spacy error

```AttributeError: 'spacy.morphology.Morphology' object has no attribute 'tag_map'```

**Version details**
**OS**: Ubuntu 18.04.6
**Python** : 3.9.13
**Spacy version**:
                      spacy==3.2.4
                      spacy-legacy==3.0.9
                      spacy-loggers==1.0.2
                      en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm- 3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl

**Comment by BramVanroy** [comment]
Are you on spacy-conll version 3.2.0? If so, please post the full stack trace. Otherwise, update to v3.2.0.

**Comment by pradeepdev-1995** [comment]
@BramVanroy  I updated to 3.2.0. But the error is still there
```AttributeError: 'spacy.morphology.Morphology' object has no attribute 'tag_map'```
