### ISSUE TITLE
How to directly convert spaCy DocBin object to coNLL format?

### ISSUE THREAD

**Issue by katreparitosh** [BramVanroy/spacy_conll#20]
Hi,

I am struggling to convert an already NER tagged spaCy DocBin object to coNLL format using the parser? It contains the sentences and the related entity spans.

Does this framework support this functionality? I am struggling to find the correct way.

Kindly help!

**Comment by BramVanroy** [comment]
> Have you taken a look at this?
> 
> https://spacy.io/universe/project/spacy-conll

What so you mean. Yes. That is the reference to this package.

**Comment by jonnyfoka** [comment]
Hey there, 

is there any update on this missing function? I happen to also have a Spacy DocBin object with already annotated sentences for relation extraction. It would be really helpful to parse it into the conll format :)

Thanks a lot :)

**Comment by BramVanroy** [comment]
Hi there @jonnyfoka 

You can add an annotation (e.g. CoNLL representation) to a DocBin by extracting the docs from the bin and then modifying them. Here is a minimal example to show you. I will also add it to the examples.

```python
import spacy
from spacy_conll import ConllFormatter
from spacy.tokens import DocBin

# Regular spaCy parsing (no CoNLL formatter)
nlp = spacy.load("en_core_web_sm")
docs = nlp.pipe(["This is a document to serialize.", "Anoter one (bites the dust)."])
doc_bin = DocBin(docs=docs)

# Adding CoNLL formatter
formatter = ConllFormatter()
# Read the docs that are in the doc_bin, and add the CoNLL representation to them
conll_docs = [formatter(doc) for doc in doc_bin.get_docs(nlp.vocab)]
conll_doc_bin = DocBin(docs=conll_docs, store_user_data=True)

# Check that it is indeed there in the new doc_bin
for conll_doc in conll_doc_bin.get_docs(nlp.vocab):
    print(conll_doc._.conll_str)

```
