### ISSUE TITLE
how to specify particular language models in init_parser()?

### ISSUE THREAD

**Issue by ghshin-github** [BramVanroy/spacy_conll#27]
Can you please let me know how to specify particular language models as a parameter of init_parser() when using spacy-stanza or spacy-udpipe? There are multiple models in many languages and not all the models follow the same tagging scheme, so sometimes we may need to use specific models for certain purposes.

**Comment by BramVanroy** [comment]
You can just pass the model name as the first argument:

```python
nlp = init_parser("en_core_web_sm", "spacy")
```

**Comment by ghshin-github** [comment]
Thanks for the prompt response. What I asked was when using spacy-stanza or spacy-udpipe, not using spacy. Is there any way to specify particular language models like the following way?

nlp = init_parser("la, perseus", "spacy-stanza")
