### ISSUE TITLE
The dependency relations aren't transformed to universal dependencies

### ISSUE THREAD

**Issue by duichwer** [BramVanroy/spacy_conll#4]
I like your project, but maybe you could extend it with a mapper that parser the dependencies from the language-specific to [universal depencies](https://universaldependencies.org/u/dep/index.html).

Or you should mention that the output looks like the [conllu format](https://universaldependencies.org/format.html,), but does not totally comply with it. 

For the language English, they are mostly the same, but e.g. for german, they differ somehow. (https://spacy.io/api/annotation#dependency-parsing)

**Comment by BramVanroy** [comment]
Hi. Yes, the module simply takes spaCy's output and puts it into the CoNLL-U format (as the Readme says). I understand what you mean, though. For English this should be okay (since the output of English models is in UD), I have not tested other models.

This would require me to test all models' tags and - more importantly - write my own tagmap, whichI am not keen to do. Not because of the work, but because I cannot be sure that it is "correct" because I don't know the tagset. If you have such a tagmap (and an authoritative source behind it), then I can implement it.

**Comment by duichwer** [comment]
Hi, 
I checked the documentation again and it seems that there are only special tags for the english and the german dependency relations used. For all other languages the universal dependencies are used.
For english the [CLEAR Style](https://github.com/clir/clearnlp-guidelines/blob/master/md/specifications/dependency_labels.md) is used
and for german they use the dependency relations of the[ tiger tree bank](https://www.ims.uni-stuttgart.de/forschung/ressourcen/korpora/tiger/).

The problem is that it's not that easy to "map", since the trees might change and they would have to be transformed.
I found one [thesis ](https://gitlab.cl.uzh.ch/siclemat/tigerdep2ud)that focus on this problem using another published [Tree transducer](https://gitlab.com/nats/TrUDucer). 

It's not that easy as I hoped.

**Comment by BramVanroy** [comment]
Exactly. I can add two features. Well, the first one is not really a feature but a recommendation: you can use this component when you use the `spacy_stanfordnlp` package, too. AFAIK the stanfordnlp models are all trained on UD data.

```python
from spacy_stanfordnlp import StanfordNLPLanguage
import stanfordnlp

from spacy_conll import ConllFormatter


snlp = stanfordnlp.Pipeline(lang='en')
nlp = StanfordNLPLanguage(snlp)
conllformatter = ConllFormatter(nlp)
nlp.add_pipe(conllformatter, last=True)

s = 'A cookie is a baked or cooked food that is typically small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts, etc.'

doc = nlp(s)

for sent in doc.sents:
    print(sent._.conll_str)
```

I will modify the CLI script to give users the option to use stanfordnlp over spaCy. 

Second, I will add a map option to the component where users can add custom maps.

I will try to do this over the next two weeks.

**Comment by BramVanroy** [comment]
Hi @duichwer 

I hope that the updated documentation and examples as well as the new feature of adding a tagmap solves your question. If not, let me know!
