### ISSUE TITLE
Disabling automatic sentence boundary detection

### ISSUE THREAD

**Issue by ranjita-naik** [BramVanroy/spacy_conll#7]
Could you please let me know how to disable automatic sentence boundary detection and parse the following input as  a single piece of text. I've tried disable_sbd , but it doesn't seem to work. 

import stanza
stanza.download('fr')
from spacy_conll import init_parser

nlp = init_parser("stanza", "fr", parser_opts={"use_gpu": True, "verbose": False}, disable_sbd=True, include_headers=True)

doc = nlp("A l&apos; opposé de ses deux prédécesseurs - Nelson Mandela le béatifié qui a mis l&apos; accent sur la fin du conflit racial et l&apos; aristocrate Thabo Mbeki , dont la maîtrise de la macroéconomie a rassuré les financiers - Zuma reconnaît la demande sous @-@ jacente d&apos; améliorer les conditions de vie matérielles des dix millions d&apos; indigents du pays . &quot; � Les erreurs commises au cours des 15 dernières années nous ont beaucoup appris , notamment la manière dont nous avons , dans une certaine mesure , négligé l &quot; évolution de la population &quot; a @-@ t @-@ il déclaré en avril , avant que son parti n&apos; emporte la victoire .")
conll = doc._.conll_str

print(conll)

# sent_id = 1
# text = A l&apos ; opposé de ses deux prédécesseurs - Nelson Mandela le béatifié qui a mis l&apos ;
1       A       à       ADP             _       2       case    _       _
2       l&apos  l&apos  PROPN           _       0       root    _       _
3       ;       ;       PUNCT           _       4       punct   _       _
4       opposé  opposer VERB    Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part        _       2       acl     _      _
5       de      de      ADP             _       8       case    _       _
6       ses     son     DET     Gender=Masc|Number=Plur|Poss=Yes|PronType=Prs   _       8       det     _       _
7       deux    deux    NUM             _       8       nummod  _       _
8       prédécesseurs   prédécesseur    NOUN    Gender=Masc|Number=Plur _       4       obl:arg _       _
9       -       -       PUNCT           _       10      punct   _       _
10      Nelson  Nelson  PROPN           _       8       appos   _       _
11      Mandela Mandela PROPN           _       10      flat:name       _       _
12      le      le      DET     Definite=Def|Gender=Masc|Number=Sing|PronType=Art       _       13      det     _      _
13      béatifié        béatifier       NOUN    Gender=Masc|Number=Sing _       10      appos   _       _
14      qui     qui     PRON    PronType=Rel    _       16      nsubj   _       _
15      a       avoir   AUX     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   _       16      aux:tense      _                                               _
16      mis     mettre  VERB    Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part        _       13      acl:relcl      _                                               _
17      l&apos  l&apos  NOUN    Gender=Masc|Number=Sing _       16      obj     _       _
18      ;       ;       PUNCT           _       4       punct   _       _

# sent_id = 2
# text = accent sur la fin de le conflit racial et l&apos ;
1       accent  accent  NOUN    Gender=Masc|Number=Sing _       0       root    _       _
2       sur     sur     ADP             _       4       case    _       _
3       la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       4       det     _      _
4       fin     fin     NOUN    Gender=Fem|Number=Sing  _       1       nmod    _       _
5       de      de      ADP             _       7       case    _       _
6       le      le      DET     Definite=Def|Gender=Masc|Number=Sing|PronType=Art       _       7       det     _      _
7       conflit conflit NOUN    Gender=Masc|Number=Sing _       4       nmod    _       _
8       racial  racial  ADJ     Gender=Masc|Number=Sing _       7       amod    _       _
9       et      et      CCONJ           _       10      cc      _       _
10      l&apos  l&apos  ADJ     Gender=Masc|Number=Sing _       8       conj    _       _
11      ;       ;       PUNCT           _       1       punct   _       _

# sent_id = 3
# text = aristocrate Thabo Mbeki , dont la maîtrise de la macroéconomie a rassuré les financiers - Zuma reconnaît la demande sous @-@ jacente d&apos ;
1       aristocrate     aristocrate     NOUN    Gender=Masc|Number=Sing _       17      nsubj   _       _
2       Thabo   Thabo   PROPN           _       1       appos   _       _
3       Mbeki   Mbeki   PROPN           _       2       flat:name       _       _
4       ,       ,       PUNCT           _       12      punct   _       _
5       dont    dont    PRON    PronType=Rel    _       7       nmod    _       _
6       la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       7       det     _      _
7       maîtrise        maîtrise        NOUN    Gender=Fem|Number=Sing  _       12      nsubj   _       _
8       de      de      ADP             _       10      case    _       _
9       la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       10      det     _      _
10      macroéconomie   macroéconomie   NOUN    Gender=Fem|Number=Sing  _       7       nmod    _       _
11      a       avoir   AUX     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   _       12      aux:tense      _                                               _
12      rassuré rassurer        VERB    Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part        _       1       acl:relcl                                              __
13      les     le      DET     Definite=Def|Gender=Masc|Number=Plur|PronType=Art       _       14      det     _      _
14      financiers      financier       NOUN    Gender=Masc|Number=Plur _       12      obj     _       _
15      -       -       PUNCT           _       12      punct   _       _
16      Zuma    Zuma    PROPN           _       17      nsubj   _       _
17      reconnaît       reconnaître     VERB    Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   _       0      root                                            __
18      la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       19      det     _      _
19      demande demande NOUN    Gender=Fem|Number=Sing  _       17      obj     _       _
20      sous    sous    ADP             _       21      case    _       _
21      @-@     @-@     NOUN    Gender=Masc|Number=Sing _       19      nmod    _       _
22      jacente jacent  ADJ     Gender=Fem|Number=Sing  _       21      amod    _       _
23      d&apos  d&apos  NOUN    Gender=Fem|Number=Sing  _       21      nmod    _       _
24      ;       ;       PUNCT           _       17      punct   _       _

# sent_id = 4
# text = améliorer les conditions de vie matérielles de les dix millions d&apos ;
1       améliorer       améliorer       VERB    VerbForm=Inf    _       0       root    _       _
2       les     le      DET     Definite=Def|Gender=Fem|Number=Plur|PronType=Art        _       3       det     _      _
3       conditions      condition       NOUN    Gender=Fem|Number=Plur  _       1       obj     _       _
4       de      de      ADP             _       5       case    _       _
5       vie     vie     NOUN    Gender=Fem|Number=Sing  _       3       nmod    _       _
6       matérielles     matériel        ADJ     Gender=Fem|Number=Plur  _       5       amod    _       _
7       de      de      ADP             _       10      case    _       _
8       les     le      DET     Definite=Def|Gender=Masc|Number=Plur|PronType=Art       _       10      det     _      _
9       dix     dix     NUM             _       10      nummod  _       _
10      millions        million NOUN    Gender=Masc|Number=Plur _       3       nmod    _       _
11      d&apos  d&apos  ADJ     Gender=Masc|Number=Plur _       10      amod    _       _
12      ;       ;       PUNCT           _       1       punct   _       _

# sent_id = 5
# text = indigents de le pays . &quot ;
1       indigents       indigent        ADJ     Gender=Masc|Number=Plur _       0       root    _       _
2       de      de      ADP             _       4       case    _       _
3       le      le      DET     Definite=Def|Gender=Masc|Number=Sing|PronType=Art       _       4       det     _      _
4       pays    pays    NOUN    Gender=Masc|Number=Sing _       1       obl:arg _       _
5       .       .       PUNCT           _       6       punct   _       _
6       &quot   &quot   X               _       1       conj    _       _
7       ;       ;       PUNCT           _       1       punct   _       _

# sent_id = 6
# text = � Les erreurs commises à le cours de les 15 dernières années nous ont beaucoup appris , notamment la manière dont nous avons , dans une certaine mesure , négligé l &quot;
1       �       �       INTJ            _       16      discourse       _       _
2       Les     le      DET     Definite=Def|Gender=Fem|Number=Plur|PronType=Art        _       3       det     _      _
3       erreurs erreur  NOUN    Gender=Fem|Number=Plur  _       16      obl:mod _       _
4       commises        commettre       VERB    Gender=Fem|Number=Plur|Tense=Past|VerbForm=Part _       3       acl    _                                               _
5       à       à       ADP             _       7       case    _       _
6       le      le      DET     Definite=Def|Gender=Masc|Number=Sing|PronType=Art       _       7       det     _      _
7       cours   cours   NOUN    Gender=Masc|Number=Sing _       4       obl:mod _       _
8       de      de      ADP             _       12      case    _       _
9       les     le      DET     Definite=Def|Gender=Fem|Number=Plur|PronType=Art        _       12      det     _      _
10      15      15      NUM             _       12      nummod  _       _
11      dernières       dernier ADJ     Gender=Fem|Number=Plur  _       12      amod    _       _
12      années  année   NOUN    Gender=Fem|Number=Plur  _       7       nmod    _       _
13      nous    il      PRON    Number=Plur|Person=1|PronType=Prs       _       16      nsubj   _       _
14      ont     avoir   AUX     Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin   _       16      aux:tense      _                                               _
15      beaucoup        beaucoup        ADV             _       16      advmod  _       _
16      appris  apprendre       VERB    Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part        _       0       root   _                                               _
17      ,       ,       PUNCT           _       20      punct   _       _
18      notamment       notamment       ADV             _       20      advmod  _       _
19      la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       20      det     _      _
20      manière manière NOUN    Gender=Fem|Number=Sing  _       16      obj     _       _
21      dont    dont    PRON    PronType=Rel    _       30      iobj    _       _
22      nous    il      PRON    Number=Plur|Person=1|PronType=Prs       _       30      nsubj   _       _
23      avons   avoir   AUX     Mood=Ind|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin   _       30      aux:tense      _                                               _
24      ,       ,       PUNCT           _       28      punct   _       _
25      dans    dans    ADP             _       28      case    _       _
26      une     un      DET     Definite=Ind|Gender=Fem|Number=Sing|PronType=Art        _       28      det     _      _
27      certaine        certain ADJ     Gender=Fem|Number=Sing  _       28      amod    _       _
28      mesure  mesure  NOUN    Gender=Fem|Number=Sing  _       30      obl:mod _       _
29      ,       ,       PUNCT           _       28      punct   _       _
30      négligé négliger        VERB    Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part        _       20      acl:relcl                                              __
31      l       le      DET     Definite=Def|Gender=Masc|Number=Sing|PronType=Art       _       32      det     _      _
32      &quot;  &quot;  NOUN    Gender=Masc|Number=Sing _       30      obj     _       _

# sent_id = 7
# text = évolution de la population &quot ;
1       évolution       évolution       NOUN    Gender=Fem|Number=Sing  _       0       root    _       _
2       de      de      ADP             _       4       case    _       _
3       la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       4       det     _      _
4       population      population      NOUN    Gender=Fem|Number=Sing  _       1       nmod    _       _
5       &quot   &quot   NOUN    Gender=Fem|Number=Sing  _       4       appos   _       _
6       ;       ;       PUNCT           _       1       punct   _       _

# sent_id = 8
# text = a @-@ t @-@ il déclaré en avril , avant que son parti n&apos ;
1       a       à       ADP             _       3       case    _       _
2       @-@     @-@     X               _       6       obl:mod _       _
3       t       t       NOUN    Gender=Masc|Number=Sing _       6       obl:mod _       _
4       @-@     @-@     X               _       3       appos   _       _
5       il      il      PRON    Gender=Masc|Number=Sing|Person=3|PronType=Prs   _       6       nsubj   _       _
6       déclaré déclarer        VERB    Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part        _       0       root   _                                               _
7       en      en      ADP             _       8       case    _       _
8       avril   avril   NOUN    Gender=Masc|Number=Sing _       6       obl     _       _
9       ,       ,       PUNCT           _       14      punct   _       _
10      avant   avant   ADP             _       14      mark    _       _
11      que     que     SCONJ           _       14      mark    _       _
12      son     son     DET     Gender=Masc|Number=Sing|Poss=Yes|PronType=Prs   _       13      det     _       _
13      parti   parti   NOUN    Gender=Masc|Number=Sing _       14      nsubj   _       _
14      n&apos  ncaposs VERB    Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   _       6       advcl   _      _
15      ;       ;       PUNCT           _       6       punct   _       _

# sent_id = 9
# text = emporte la victoire .
1       emporte emporter        VERB    Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   _       0       root   _                                               _
2       la      le      DET     Definite=Def|Gender=Fem|Number=Sing|PronType=Art        _       3       det     _      _
3       victoire        victoire        NOUN    Gender=Fem|Number=Sing  _       1       obj     _       _
4       .       .       PUNCT           _       1       punct   _       _

thanks,
Ranjita

**Comment by BramVanroy** [comment]
@ranjita-naik Hi there, can you use [code blocks](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) with `python`? I'm not able to run your code because there is an issue with the text that you provided. There are quotation marks inside the outer quotation marks, which is not valid in Python. If you can provide me with some test data I can check.

**Comment by BramVanroy** [comment]
The issue is that `disable_sbd` only works for spaCy, not for `stanza`, as is written in the docstring. You can use `is_tokenized` instead for stanza, but this will also disable tokenization. There is currently no other way for non-spacy frameworks.

**Comment by ranjita-naik** [comment]
Thanks for the quick response. Please find the code below. 

```
import stanza
stanza.download('fr')
from spacy_conll import init_parser
nlp = init_parser("stanza", "fr", parser_opts={"use_gpu": True, "verbose": False}, disable_sbd=True, include_headers=True)
doc = nlp("A l&apos; opposé de ses deux prédécesseurs - Nelson Mandela le béatifié qui a mis l&apos; accent sur la fin du conflit racial et l&apos; aristocrate Thabo Mbeki , dont la maîtrise de la macroéconomie a rassuré les financiers - Zuma reconnaît la demande sous @-@ jacente d&apos; améliorer les conditions de vie matérielles des dix millions d&apos; indigents du pays . &quot; � Les erreurs commises au cours des 15 dernières années nous ont beaucoup appris , notamment la manière dont nous avons , dans une certaine mesure , négligé l &quot; évolution de la population &quot; a @-@ t @-@ il déclaré en avril , avant que son parti n&apos; emporte la victoire .")
conll = doc._.conll_str
print(conll)

```

**Comment by BramVanroy** [comment]
Please see my second comment. You cannot use disabled_sbd with stanza. Instead you should use `is_tokenized` but this will also disable tokenization.

**Comment by ranjita-naik** [comment]
Got it. Thanks.

**Comment by matgrioni** [comment]
Just an update on this that it seems this is now supported via this [PR](https://github.com/BramVanroy/spacy_conll/commit/2cf0c7924c1bdbf74d1739a9ecb6c544084499f5). The information on the issue confused me and I had to check the code.

**Comment by BramVanroy** [comment]
@matgrioni If I remember correctly I indeed implemented this for stanza as well after stanza update things on their end. They now allow disabling sentence boundary detection and [just split on double newlines](https://stanfordnlp.github.io/stanza/tokenize.html#tokenization-without-sentence-segmentation).
